#!/usr/bin/env bash

on(){
    OPTION="${1:---left-of}"
    xrandr --output DP-0 --auto "$OPTION" HDMI-0 --rotate left 
}

off(){
    xrandr --output DP-0 --off
}

restore(){
    ~/.fehbg & 
}

case $1 in
    "off") off;;
    *) on $1;;
esac

restore
