#!/usr/bin/env bash

arch() {
    pacman -Qqen > requirements/pkglist.txt
    pacman -Qqem > requirements/pkglist_aur.txt
    cargo install --list | rg -v rust-analyzer > requirements/cargo_install_list.txt
    code --list-extensions > requirements/vscode-extensions.txt
}

mac() {
    # todo
    :
}

case `uname` in
    "Linux") arch;;
    # "Darwin") mac;;
esac
