#!/usr/bin/env bash

arch() {
    pacman -Qqen > requirements/pkglist.txt
    pacman -Qqem > requirements/pkglist_aur.txt
    # I want to filter local installed ones...
    # cargo install --list > requirements/cargo_install_list.txt
}

mac() {
    # todo
    :
}

case `uname` in
    "Linux") arch;;
    # "Darwin") mac;;
esac
