#! /usr/bin/env python3
import subprocess
import time

def run(cmd):
    result = subprocess.run(cmd, stdout=subprocess.PIPE)
    return result.stdout.decode("utf-8")

while True:
    status = [run(cmd) for cmd in ['cpu','memory','traffic','clock']]
    run(['xsetroot','-name'," ".join(status)])
    time.sleep(1)
