#! /usr/bin/env python3
import json
import os
import sys

def update():
    try:
        with open('package.json', 'r') as f:
            pkg_json = json.loads(f.read())
    except:
        print('error read package.json')
        return

    dependencies = pkg_json.get('dependencies')
    devDependencies = pkg_json.get('devDependencies')
    extraArgv = " ".join(sys.argv[1:])

    if dependencies:
        pkgs = [*dependencies]
        print("📦update dependencies: ", pkgs)
        os.system(f"yarn add {extraArgv} " + " ".join(pkgs))

    if devDependencies:
        pkgs = [*devDependencies]
        print("⚙️update devDependencies: ", pkgs)
        os.system(f"yarn add {extraArgv} -D " + " ".join(pkgs))

if __name__ == '__main__':
    update()
